config/routes.rb
Rails.application.routes.draw do
  resources :produto_vendas

  resources :vendas do
    resources :produto_vendas	 
  end

  resources :clientes

  resources :produtos
  
  root :to => "vendas#index"

end

app/models/produto_venda.rb
class ProdutoVenda < ActiveRecord::Base
  belongs_to :venda
  belongs_to :produto
end

app/controllers/produto_vendas_controller.rb
class ProdutoVendasController < ApplicationController
  before_action :set_produto_venda, only: [:show, :edit, :update, :destroy]

  # GET /produto_vendas
  # GET /produto_vendas.json
  def index
    @produto_vendas = ProdutoVenda.all
  end

  # GET /produto_vendas/1
  # GET /produto_vendas/1.json
  def show
  end

  # GET /produto_vendas/new
  def new
    @produto_venda = ProdutoVenda.new
  end

  # GET /produto_vendas/1/edit
  def edit
  end

  # POST /produto_vendas
  # POST /produto_vendas.json
  def create
    @produto_venda = ProdutoVenda.new(produto_venda_params)
    @produto_venda.valor_venda = @produto_venda.produto.valor_venda
    respond_to do |format|
      if @produto_venda.save
        format.html { redirect_to @produto_venda.venda, notice: 'Produto venda was successfully created.' }
        format.json { render :show, status: :created, location: @produto_venda }
      else
        format.html { render :new }
        format.json { render json: @produto_venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produto_vendas/1
  # PATCH/PUT /produto_vendas/1.json
  def update
    respond_to do |format|
      if @produto_venda.update(produto_venda_params)
        format.html { redirect_to @produto_venda.venda, notice: 'Produto venda was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto_venda }
      else
        format.html { render :edit }
        format.json { render json: @produto_venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produto_vendas/1
  # DELETE /produto_vendas/1.json
  def destroy
    @produto_venda.destroy
    respond_to do |format|
      format.html { redirect_to @produto_venda.venda, notice: 'Produto venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto_venda
      @produto_venda = ProdutoVenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_venda_params
      params.require(:produto_venda).permit(:valor_venda, :quantidade, :venda_id, :produto_id, :observacao)
    end
end

app/helpers/produto_vendas_helper.rb
module ProdutoVendasHelper
end

app/views/produto_vendas/_form.html.erb
<%= form_for(@produto_venda) do |f| %>
  <% if @produto_venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto_venda.errors.count, "error") %> prohibited this produto_venda from being saved:</h2>

      <ul>
      <% @produto_venda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor_venda %><br>
    <%= f.text_field :valor_venda %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.text_field :quantidade %>
  </div>
  <div class="field">
    <%= f.label :venda_id %><br>
    <%= f.text_field :venda_id %>
  </div>
  <div class="field">
    <%= f.label :produto_id %><br>
    <%= f.text_field :produto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produto_vendas/edit.html.erb
<h1>Editing produto_venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto_venda %> |
<%= link_to 'Back', produto_vendas_path %>

app/views/produto_vendas/index.html.erb
<h1>Listing produto_vendas</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Nome</th>  
      <th>Valor venda</th>
      <th>Quantidade</th>
      <th>Venda</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produto_vendas.each do |produto_venda| %>
      <tr>
        <td><%= produto_venda.produto %></td>  
        <td><%= produto_venda.valor_venda %></td>
        <td><%= produto_venda.quantidade %></td>
        <td><%= produto_venda.venda %></td>
        <td><%= produto_venda.produto %></td>
        <td><%= link_to 'Show', produto_venda %></td>
        <td><%= link_to 'Edit', edit_produto_venda_path(produto_venda) %></td>
        <td><%= link_to 'Destroy', produto_venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto venda', new_produto_venda_path %>

app/views/produto_vendas/new.html.erb
<h1>New produto_venda</h1>

<%= render 'form' %>

<%= link_to 'Back', produto_vendas_path %>

app/views/produto_vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor venda:</strong>
  <%= @produto_venda.valor_venda %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto_venda.quantidade %>
</p>

<p>
  <strong>Venda:</strong>
  <%= @produto_venda.venda %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @produto_venda.produto %>
</p>

<%= link_to 'Edit', edit_produto_venda_path(@produto_venda) %> |
<%= link_to 'Back', produto_vendas_path %>